Add basic UEFI code to load memory map
colescott/yao pull request #1
Opened 2018-04-25 03:33 UTC by colescott

2018-04-28 04:27 UTC, eliaslfox requested changes

2018-04-28 04:27 UTC, eliaslfox commented on default.nix
> +    qemu OVMF
this needs a newline

2018-04-28 04:27 UTC, eliaslfox commented on uefi/Makefile
> +CC=gcc
Is this compatible with non gnu systems?

2018-04-28 04:27 UTC, eliaslfox commented on .astylerc
> +style=mozilla
I don't like mozilla

2018-04-28 04:28 UTC, eliaslfox submitted a review, later dismissed

2018-04-28 04:37 UTC, eliaslfox requested changes
-Werror

2018-04-28 05:04 UTC, eliaslfox submitted a review, later dismissed

2018-05-04 20:34 UTC, eliaslfox approved these changes
Although I have strong reservations on the indentation of just about all of the c code in this pr. I think that the make files alone are dank enough to justify merging.

2018-05-05 01:29 UTC, rizend approved these changes

2018-05-05 01:37 UTC, merged